-- ============================================
-- Lab 10 JPA Schema (auto-generated by Hibernate)
-- This file is for reference only
-- ============================================

-- User table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    phone VARCHAR(50),
    active BOOLEAN DEFAULT TRUE,
    created_at DATETIME,
    updated_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Login logs table
CREATE TABLE IF NOT EXISTS login_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    email VARCHAR(100),
    action VARCHAR(20),
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    logged_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SinhVien table
CREATE TABLE IF NOT EXISTS sinh_vien (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ma_sv VARCHAR(20) NOT NULL UNIQUE,
    ho_ten VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    lop VARCHAR(50),
    ngay_sinh DATE,
    active BOOLEAN DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MonHoc table
CREATE TABLE IF NOT EXISTS mon_hoc (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ma_mon VARCHAR(20) NOT NULL UNIQUE,
    ten_mon VARCHAR(100) NOT NULL,
    so_tin_chi INT,
    active BOOLEAN DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Diem table
CREATE TABLE IF NOT EXISTS diem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sinh_vien_id INT,
    mon_hoc_id INT,
    diem_gk DECIMAL(4,2),
    diem_ck DECIMAL(4,2),
    diem_tong_ket DECIMAL(4,2),
    xep_loai VARCHAR(20),
    FOREIGN KEY (sinh_vien_id) REFERENCES sinh_vien(id) ON DELETE CASCADE,
    FOREIGN KEY (mon_hoc_id) REFERENCES mon_hoc(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
